<?php
/**
 * Mapa centralizado de cores dos atos notariais.
 *
 * Usado tanto pelo PHP (card.php) quanto exportado como JSON
 * para o JavaScript consumir via api/ato-cores.php.
 *
 * Para adicionar ou alterar uma cor basta editar este arquivo.
 */
return [
    'Abertura de Crédito em conta' => '#3b82f6',
    'Aditivo' => '#22c55e',
    'Alienação Fiduciária' => '#f97316',
    'Ata de adjudicação compulsória' => '#6366f1',
    'Ata Notarial Diligencia Externa' => '#14b8a6',
    'Ata Notarial Externa' => '#0ea5e9',
    'Ata Notarial Interna' => '#8b5cf6',
    'Ata Notarial Internet' => '#ef4444',
    'Ata Notarial para Usucapião' => '#06b6d4',
    'Autocuratela' => '#84cc16',
    'Autorização' => '#a855f7',
    'Caução' => '#f59e0b',
    'Cessão de direitos de aquisição' => '#10b981',
    'Cessão de Direitos de Meação Onerosa' => '#1d4ed8',
    'Cessão de Direitos de Meação por Doação' => '#f43f5e',
    'Cessão de Direitos de Posse' => '#16a34a',
    'Cessão de Direitos Hereditários' => '#0f766e',
    'Cessão de Direitos Hereditários e de Meação' => '#7c3aed',
    'Cessão de Direitos Não Onerosa' => '#ea580c',
    'Cessão de Direitos Onerosa' => '#2563eb',
    'Comodato' => '#059669',
    'Compra e venda' => '#4f46e5',
    'Compra e Venda Bem Móvel com Hipoteca e Alienação' => '#b45309',
    'Compra e Venda com Cessão Onerosa de Direito de Us' => '#0891b2',
    'Compromisso de Compra e Venda' => '#22c55e',
    'Concessão de Direito Real de Uso' => '#f97316',
    'Confissão de Dívida' => '#64748b',
    'Constituição e Convenção de Condomínio' => '#0ea5e9',
    'Contrato de Arrendamento Mercantil' => '#1f2937',
    'Contrato de Locação' => '#0f766e',
    'Conversão de separação em divórcio sem partilha' => '#7c3aed',
    'CONVERSÃO Escritura pública' => '#e11d48',
    'Dação em Pagamento' => '#16a34a',
    'Declaração de União Estável' => '#9333ea',
    'Declaratória' => '#f59e0b',
    'Declaratória de Estremação' => '#0ea5e9',
    'Desapropriação' => '#ef4444',
    'Desapropriação Amigável' => '#10b981',
    'Desfazimento' => '#f97316',
    'Desincorporação' => '#6366f1',
    'Diretivas Antecipadas de Vontade' => '#14b8a6',
    'Dissolução de União Estável' => '#3b82f6',
    'Dissolução de União Estável Com Partilha' => '#22c55e',
    'Distrato de Escritura Pública' => '#f43f5e',
    'Divisão Amigável' => '#0ea5e9',
    'Divórcio com Partilha' => '#8b5cf6',
    'Divórcio Sem Partilha' => '#ef4444',
    'Doação' => '#f59e0b',
    'Doação com Reserva de Usufruto' => '#10b981',
    'Emancipação' => '#6366f1',
    'Extinção de Fundação' => '#0f766e',
    'Hipoteca' => '#f97316',
    'Incorporação' => '#3b82f6',
    'Instituição de Bem de Família' => '#14b8a6',
    'Instituição de Condomínio' => '#8b5cf6',
    'Instituição de Servidão' => '#ef4444',
    'Instituição de Usufruto' => '#22c55e',
    'Integralização de Capital' => '#0ea5e9',
    'Inventário' => '#f59e0b',
    'Inventário e Partilha com Menores e Incapazes' => '#7c3aed',
    'Inventário e Partilha de Bens' => '#10b981',
    'Mútuo' => '#64748b',
    'Nomeação de Inventariante' => '#3b82f6',
    'Nomeação de inventariante com menores e incapazes' => '#22c55e',
    'Pacto Antenupcial' => '#f97316',
    'Pacto Pós Nupcial' => '#6366f1',
    'Partilha Amigável' => '#14b8a6',
    'Permuta' => '#ef4444',
    'Pública Forma' => '#8b5cf6',
    'Quitação' => '#0ea5e9',
    'Ratificação' => '#10b981',
    'Re-Ratificação' => '#f59e0b',
    'Reconhecimento com dissolução de união estável e P' => '#64748b',
    'Reconhecimento de Paternidade' => '#3b82f6',
    'Renúncia' => '#ef4444',
    'Renúncia de Direitos Hereditários' => '#8b5cf6',
    'Renúncia de Propriedade' => '#0ea5e9',
    'Renúncia de Usufruto' => '#10b981',
    'Rerratificação' => '#f97316',
    'Rerratificação e Aditamento' => '#6366f1',
    'Restabelecimento de Sociedade Conjugal' => '#14b8a6',
    'Retificação' => '#22c55e',
    'Revogação de Clausula de Incomunicabilidade' => '#f59e0b',
    'Revogação de Cláusula de Reversão' => '#0ea5e9',
    'Revogação Procuração (1)' => '#ef4444',
    'Sobrepartilha' => '#8b5cf6',
    'Subrogação' => '#10b981',
    'Transação - Acordo Extrajudicial' => '#3b82f6',
];
